"""add_video_path_to_shots

Revision ID: fcae66ea5e4b
Revises: 1239ffa4cbf8
Create Date: 2026-09-12 15:39:02.896945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcae66ea5e4b'
down_revision: Union[str, Sequence[str], None] = '1239ffa4cbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('video_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shots', 'video_path')
    # ### end Alembic commands ###
